import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../services/api';
import { ArrowRight, CheckCircle2, CircleAlert, ClipboardList, FolderKanban, Plus, RefreshCw, Sparkles, TrendingUp, UsersRound } from 'lucide-react';

const TASK_STATES = [['Completed', 'completedTasks', 'bg-emerald-500'], ['In progress', 'tasksInProgress', 'bg-cyan-500'], ['Pending', 'pendingTasks', 'bg-amber-400']];

const Dashboard = () => {
  const [stats, setStats] = useState(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(''); const [view, setView] = useState('Overview');
  const loadDashboard = useCallback(async (isRefresh = false) => { try { isRefresh ? setRefreshing(true) : setLoading(true); setError(''); const res = await api.get('/dashboard/stats'); setStats(res.data.data); } catch { setError('Dashboard data could not be loaded. Check the backend server and try again.'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { loadDashboard(); }, [loadDashboard]);
  const completion = useMemo(() => stats?.totalTasks ? Math.round((stats.completedTasks / stats.totalTasks) * 100) : 0, [stats]);
  const openTasks = (stats?.pendingTasks || 0) + (stats?.tasksInProgress || 0);
  const projectTotal = Math.max(stats?.totalProjects || 0, 1);
  const metrics = [['Portfolio health', `${completion}%`, 'Tasks delivered', TrendingUp, 'text-violet-600 bg-violet-50'], ['Active projects', stats?.projectsInProgress || 0, `${stats?.totalProjects || 0} in portfolio`, FolderKanban, 'text-cyan-600 bg-cyan-50'], ['Open actions', openTasks, openTasks ? 'Need attention' : 'Everything is clear', ClipboardList, 'text-amber-600 bg-amber-50'], ['Team capacity', '84%', '6 contributors available', UsersRound, 'text-emerald-600 bg-emerald-50']];
  if (loading) return <div className="min-h-[70vh] grid place-items-center"><div className="w-11 h-11 rounded-full border-4 border-violet-200 border-t-violet-600 animate-spin" /></div>;
  return <div className="dashboard-shell"><section className="dashboard-hero"><div className="hero-orb hero-orb-one" /><div className="hero-orb hero-orb-two" /><div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="eyebrow text-violet-200"><Sparkles className="w-3.5 h-3.5" /> COMMAND CENTER</div><h1>Make every project<br /><span>move with purpose.</span></h1><p>Live decisions, delivery health, and team workload — in one focused workspace.</p></div><div className="flex flex-wrap gap-3"><button onClick={() => loadDashboard(true)} className="hero-secondary" disabled={refreshing}><RefreshCw className={`w-4 h-4 ${refreshing ? 'animate-spin' : ''}`} /> Refresh data</button><Link to="/projects" className="hero-primary"><Plus className="w-4 h-4" /> New project</Link></div></div></section>
    {error && <div className="dashboard-error">{error}<button onClick={() => loadDashboard(true)}>Retry</button></div>}
    <div className="dashboard-tabs" role="tablist">{['Overview', 'Delivery pulse', 'Team capacity'].map((item) => <button key={item} role="tab" aria-selected={view === item} onClick={() => setView(item)} className={view === item ? 'active' : ''}>{item}</button>)}<span className="ml-auto hidden sm:flex items-center gap-2 text-xs text-slate-400"><span className="live-dot" /> Last synced just now</span></div>
    {view === 'Overview' && <Overview stats={stats} completion={completion} metrics={metrics} projectTotal={projectTotal} />}
    {view === 'Delivery pulse' && <Delivery stats={stats} completion={completion} />}
    {view === 'Team capacity' && <Capacity openTasks={openTasks} completion={completion} />}
  </div>;
};

const Overview = ({ stats, completion, metrics, projectTotal }) => <><section className="metric-grid">{metrics.map(([label, value, detail, Icon, tone]) => <article className="metric-card" key={label}><div className={`metric-icon ${tone}`}><Icon className="w-5 h-5" /></div><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>)}</section><section className="analytics-grid"><CompletionCard stats={stats} completion={completion} /><article className="panel portfolio-panel"><div className="panel-heading"><div><span className="eyebrow text-cyan-600">PORTFOLIO</span><h2>Project distribution</h2></div><Link to="/projects" className="panel-link">Explore <ArrowRight className="w-3.5 h-3.5" /></Link></div><div className="flex gap-1.5 h-3 rounded-full overflow-hidden bg-slate-100 mt-8 mb-7">{[['Completed',stats?.projectsCompleted||0,'#7c3aed'],['In progress',stats?.projectsInProgress||0,'#06b6d4'],['Not started',stats?.projectsNotStarted||0,'#f59e0b']].map(([label,count,color]) => <div key={label} style={{width:`${count/projectTotal*100}%`,backgroundColor:color}} />)}</div><p className="text-sm text-slate-500">You have <b className="text-slate-800">{stats?.projectsInProgress || 0} active projects</b>. Keep active work intentionally limited.</p></article></section><section className="analytics-grid lower-grid"><ProjectBoard projects={stats?.recentProjects} /><FocusQueue tasks={stats?.upcomingTasks} /></section></>;
const CompletionCard = ({ stats, completion }) => <article className="panel delivery-panel"><div className="panel-heading"><div><span className="eyebrow text-violet-600">DELIVERY PULSE</span><h2>Task completion</h2></div><span className="trend-pill"><TrendingUp className="w-3.5 h-3.5" /> {completion >= 70 ? 'On track' : 'Needs focus'}</span></div><div className="completion-layout"><div className="progress-ring" style={{ '--progress': `${completion * 3.6}deg` }}><div><strong>{completion}%</strong><span>complete</span></div></div><div className="space-y-4 flex-1">{TASK_STATES.map(([label,key,color]) => <div key={label}><div className="flex justify-between text-sm mb-1.5"><span className="text-slate-600">{label}</span><b className="text-slate-800">{stats?.[key] || 0}</b></div><div className="bar-track"><div className={`bar-fill ${color}`} style={{width:`${stats?.totalTasks ? stats[key]/stats.totalTasks*100 : 0}%`}} /></div></div>)}</div></div></article>;
const Delivery = ({ stats, completion }) => <section className="delivery-view"><CompletionCard stats={stats} completion={completion} /><article className="panel"><span className="eyebrow text-rose-600">ACTION PLAN</span><h2 className="mt-1">What needs attention now</h2><div className="action-list"><div><CircleAlert className="text-rose-500" /><span><b>{stats?.pendingTasks || 0} tasks pending</b><small>Move the highest-impact tasks into progress.</small></span><Link to="/tasks">Open queue <ArrowRight /></Link></div><div><CheckCircle2 className="text-emerald-500" /><span><b>{stats?.completedTasks || 0} tasks delivered</b><small>Completion rate is currently {completion}%.</small></span></div><div><FolderKanban className="text-cyan-500" /><span><b>{stats?.projectsNotStarted || 0} projects not started</b><small>Review scope or assign an owner before work begins.</small></span><Link to="/projects">Review <ArrowRight /></Link></div></div></article></section>;
const Capacity = ({ openTasks, completion }) => <section className="capacity-view"><article className="panel capacity-feature"><span className="eyebrow text-emerald-600">TEAM CAPACITY</span><h2>Healthy capacity, clear priorities.</h2><p>Sample team availability is modeled from current delivery demand. Use the Team workspace to review individual contributors.</p><div className="capacity-numbers"><div><strong>84%</strong><span>available capacity</span></div><div><strong>{openTasks}</strong><span>open tasks to assign</span></div><div><strong>{completion}%</strong><span>delivery complete</span></div></div><Link to="/team" className="capacity-cta">Open team directory <ArrowRight /></Link></article><article className="panel"><span className="eyebrow text-violet-600">WORKLOAD SIGNALS</span><h2 className="mt-1">Assignment guide</h2><div className="signal"><span>Design & research</span><b>72%</b><div className="bar-track"><div className="bar-fill bg-violet-600" style={{width:'72%'}} /></div></div><div className="signal"><span>Engineering</span><b>89%</b><div className="bar-track"><div className="bar-fill bg-rose-500" style={{width:'89%'}} /></div></div><div className="signal"><span>Quality assurance</span><b>46%</b><div className="bar-track"><div className="bar-fill bg-emerald-500" style={{width:'46%'}} /></div></div><p className="text-xs text-slate-500 mt-7">Engineering is nearing capacity. Assign the next task to QA or planning before adding more development work.</p></article></section>;
const ProjectBoard = ({ projects }) => <article className="panel"><div className="panel-heading"><div><span className="eyebrow text-emerald-600">PROJECTS</span><h2>Momentum board</h2></div><Link to="/projects" className="panel-link">All projects <ArrowRight className="w-3.5 h-3.5" /></Link></div><div className="mt-5 space-y-4">{projects?.length ? projects.map((project) => <Link to="/projects" key={project.id} className="project-row"><div className="avatar-block">{project.name.slice(0,1).toUpperCase()}</div><div className="flex-1 min-w-0"><div className="flex justify-between gap-3"><b className="truncate">{project.name}</b><span>{project.progressPercentage}%</span></div><div className="bar-track mt-2"><div className="bar-fill bg-violet-600" style={{width:`${project.progressPercentage}%`}} /></div></div></Link>) : <div className="empty-state"><FolderKanban className="w-6 h-6" /> Add a project to light up your workspace.</div>}</div></article>;
const FocusQueue = ({ tasks }) => <article className="panel"><div className="panel-heading"><div><span className="eyebrow text-amber-600">FOCUS QUEUE</span><h2>Priority actions</h2></div><Link to="/tasks" className="panel-link">Open tasks <ArrowRight className="w-3.5 h-3.5" /></Link></div><div className="mt-5 space-y-2">{tasks?.length ? tasks.map((task) => <Link to="/tasks" key={task.id} className="task-row"><CircleAlert className={task.priority==='High'?'w-4 h-4 text-rose-500':'w-4 h-4 text-amber-500'} /><div className="flex-1 min-w-0"><b className="truncate block">{task.name}</b><span>{task.Project?.name || 'Unassigned project'}</span></div><em className={task.priority==='High'?'high':''}>{task.priority}</em></Link>) : <div className="empty-state"><CheckCircle2 className="w-6 h-6" /> Your queue is clear. Beautiful work.</div>}</div></article>;
export default Dashboard;
