import React, { useEffect, useState } from 'react';
import api from '../services/api';
import { CheckCircle2, ExternalLink, GitBranch, Loader2, PlugZap, RefreshCw, Unplug } from 'lucide-react';

const Integrations = () => {
  const [status, setStatus] = useState(null); const [repos, setRepos] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { try { setLoading(true); setError(''); const result = await api.get('/integrations/github/status'); setStatus(result.data.data); if (result.data.data.connected) { const repoResult = await api.get('/integrations/github/repositories'); setRepos(repoResult.data.data); } } catch (err) { setError(err.response?.data?.error || 'Could not load GitHub integration.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const connect = async () => { try { const result = await api.post('/integrations/github/connect'); window.location.assign(result.data.data.authorizationUrl); } catch (err) { setError(err.response?.data?.error || 'GitHub OAuth could not be started.'); } };
  const disconnect = async () => { if (!window.confirm('Disconnect GitHub from this PlanFlow account?')) return; await api.delete('/integrations/github'); setRepos([]); load(); };
  if (loading) return <div className="min-h-[60vh] grid place-items-center"><Loader2 className="w-9 h-9 text-violet-600 animate-spin" /></div>;
  return <div className="integration-page"><section className="integration-hero"><div><span className="eyebrow text-violet-200"><PlugZap className="w-3.5 h-3.5" /> WORKSPACE INTEGRATIONS</span><h1>Connect the work.<br /><span>See the whole story.</span></h1><p>Bring GitHub repositories, pull requests, and engineering momentum into PlanFlow.</p></div><GitBranch className="github-mark" /></section>{error && <div className="dashboard-error">{error}<button onClick={load}>Retry</button></div>}<section className="integration-card"><div className="integration-logo"><GitBranch /></div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2>GitHub</h2>{status?.connected ? <span className="connected-badge"><CheckCircle2 /> Connected</span> : <span className="not-connected">Not connected</span>}</div><p>{status?.connected ? `Connected as @${status.githubLogin}. Repository data is available below.` : 'Connect your GitHub account securely through GitHub OAuth.'}</p></div>{status?.connected ? <button className="disconnect-button" onClick={disconnect}><Unplug /> Disconnect</button> : <button className="connect-button" onClick={connect}><GitBranch /> Connect GitHub</button>}</section>{status?.connected && <section className="repo-panel"><div className="panel-heading"><div><span className="eyebrow text-violet-600">SYNCHRONIZED REPOSITORIES</span><h2>Your GitHub workspace</h2></div><button className="refresh-icon" onClick={load}><RefreshCw className="w-4 h-4" /> Refresh</button></div>{repos.length ? <div className="repo-grid">{repos.map((repo) => <a href={repo.url} key={repo.id} target="_blank" rel="noreferrer" className="repo-card"><div><GitBranch className="w-5 h-5" /><span>{repo.private ? 'Private' : 'Public'}</span></div><h3>{repo.name}</h3><p>{repo.language || 'Repository'} · {repo.openIssues} open issues</p><small>Updated {new Date(repo.updatedAt).toLocaleDateString()} <ExternalLink /></small></a>)}</div> : <div className="empty-state"><GitBranch className="w-6 h-6" /> No accessible repositories found.</div>}</section>}</div>;
};
export default Integrations;
