import React, { useMemo, useState } from 'react';
import { Mail, MapPin, Search, SlidersHorizontal, Sparkles, UsersRound } from 'lucide-react';

const people = [
  { name: 'Ananya Rao', role: 'Product Designer', initials: 'AR', color: 'bg-violet-600', location: 'Chennai, IN', load: 72, projects: 3, status: 'Focused' }, { name: 'Karthik S', role: 'Frontend Engineer', initials: 'KS', color: 'bg-cyan-600', location: 'Bengaluru, IN', load: 88, projects: 4, status: 'In sprint' }, { name: 'Meera Iyer', role: 'Project Manager', initials: 'MI', color: 'bg-rose-500', location: 'Coimbatore, IN', load: 64, projects: 2, status: 'Available' }, { name: 'Rohan Das', role: 'Backend Engineer', initials: 'RD', color: 'bg-amber-500', location: 'Hyderabad, IN', load: 91, projects: 4, status: 'In sprint' }, { name: 'Divya Nair', role: 'QA Specialist', initials: 'DN', color: 'bg-emerald-600', location: 'Kochi, IN', load: 46, projects: 2, status: 'Available' }, { name: 'Arjun Kumar', role: 'Data Analyst', initials: 'AK', color: 'bg-indigo-600', location: 'Chennai, IN', load: 58, projects: 2, status: 'Focused' }
];

const Team = () => {
  const [query, setQuery] = useState('');
  const filtered = useMemo(() => people.filter((person) => `${person.name} ${person.role}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <div className="team-page"><section className="team-hero"><div><div className="eyebrow text-violet-200"><Sparkles className="w-3.5 h-3.5" /> SAMPLE TEAM DIRECTORY</div><h1>The people behind<br /><span>the progress.</span></h1><p>A beautiful, at-a-glance view of your project crew and their current capacity.</p></div><div className="team-stat"><UsersRound /><strong>6</strong><span>active contributors</span></div></section><div className="team-toolbar"><div className="search-box"><Search className="w-4 h-4" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Find a teammate or role..." /></div><button><SlidersHorizontal className="w-4 h-4" /> Capacity</button></div><div className="team-grid">{filtered.map((person) => <article className="person-card" key={person.name}><div className="flex justify-between"><div className={`person-avatar ${person.color}`}>{person.initials}</div><span className={`status-dot ${person.status === 'Available' ? 'available' : ''}`}>{person.status}</span></div><h2>{person.name}</h2><p className="person-role">{person.role}</p><div className="person-meta"><span><MapPin />{person.location}</span><span><Mail />{person.name.toLowerCase().replace(' ', '.')}@planflow.io</span></div><div className="capacity"><div><span>Capacity</span><b>{person.load}%</b></div><div className="bar-track"><div className={`bar-fill ${person.load > 85 ? 'bg-rose-500' : 'bg-violet-600'}`} style={{ width: `${person.load}%` }} /></div><small>{person.projects} active projects</small></div></article>)}</div></div>;
};
export default Team;
